version: '2'
services:
    myapp-app:
        image: app
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SHANGRILLA_SLEEP=30 # gives time for the JHipster Registry to boot before the application
        ports:
            - 8080:8080
